{% set name = "wasmtime-py" %}
{% set version = "29.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bytecodealliance/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b0534181f7e2c290df51b08c075f91ddfe5623cc8a323e817ecf4e2a33125c34
  patches:
    patches/0001-read-library.patch

build:
  #skip: True # [py<39 or (linux and (s390x or ppc64le))]
  skip: True # [py<39 or s390x]
  #script: {{ PYTHON }} -m pip install . -vv  --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    #- {{ compiler('rust-std-host') }}  # --> rust-std-host-h<osx-arm64_hash>.tar.bz2
    - rust-std-wasm32-wasip1
    - patch         # [unix]
    - m2-patch      # [win]
  host:
    - python
    - pip
    - wheel
    - wasmtime
    - setuptools
  run:
    - python
    - wasmtime
    - importlib-resources

test:
  source_files:
    - tests
  imports:
    - wasmtime 
  commands:
    - pip check 
    # - pytest -vv . --ignore="tests/bindgen" --ignore="tests/codegen"
    - pytest -vv .
  requires:
    - pip
    - pytest

about:
  home: https://github.com/bytecodealliance/wasmtime-py
  summary: python bindings for Wasmtime
  description: |
   The wasmtime-py package has initial support for running WebAssembly components in Python with high-level bindings. 

  license_family: Apache
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE
  dev_url: https://github.com/bytecodealliance/wasmtime-py
  doc_url: https://docs.wasmtime.dev/lang-python.html

extra:
  recipe-maintainers:
    - markw77
