{% set name = "wasmtime-py" %}
{% set version = "29.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bytecodealliance/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: b0534181f7e2c290df51b08c075f91ddfe5623cc8a323e817ecf4e2a33125c34
  patches:
    patches/0001-read-library.patch

build:
  skip: True  # [py<39]
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - rust-std-wasm32-wasip1
    - patch         # [unix]
    - m2-patch      # [win]
  host:
    - python
    - pip !=25.1
    - wheel
    - setuptools
    - wasmtime 29.0.0
  run:
    - python
    - wasmtime 29.0.0
    - importlib-resources

{% set ignore_tests = "" %}
# codegen tests unstable on linux
{% set ignore_tests = " --ignore=tests/codegen" %}  # [linux]
# raise RuntimeError("Could not find componentize-py executable.")
# {% set tests_to_skip = "test_bare_funcs" %}
# {% set tests_to_skip = tests_to_skip + " or test_lists" %}
# {% set tests_to_skip = tests_to_skip + " or test_config" %}

test:
  source_files:
    - tests
  imports:
    - wasmtime 
  commands:
    - pip check 
    - pytest -vv -k {{ ignore_tests }} .
  requires:
    - pip !=25.1
    - pytest

about:
  home: https://github.com/bytecodealliance/wasmtime-py
  summary: python bindings for Wasmtime
  description: |
   The wasmtime-py package has initial support for running WebAssembly components in Python with high-level bindings. 

  license_family: Apache
  license: Apache-2.0 WITH LLVM-exception
  license_file: LICENSE
  dev_url: https://github.com/bytecodealliance/wasmtime-py
  doc_url: https://docs.wasmtime.dev/lang-python.html

extra:
  recipe-maintainers:
    - markw77
  skip-lints:
    - missing_test_requirement_pip
